name: runtests
on: [push]
jobs:
  runtests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1.6.2"
      - run: > julia <<EOF
          using Pkg
          Pkg.instantiate()
          EOF
      - run: julia --project runtests.jl
        working-directory: ./code/test
